### ISSUE TITLE
a

### ISSUE THREAD

**Issue by siphiuel** [siphiuel/ob-test#10]

**Comment by commiteth** [comment]
![Contract deploying](http://194.44.239.202:3003/img/deploying_contract.png)
Transaction: [0xe4b7c384e11e61a2c275b097aeacd742a6fe4543c78f4d45a9a8ffa8a59ed5ee](https://ropsten.etherscan.io/tx/0xe4b7c384e11e61a2c275b097aeacd742a6fe4543c78f4d45a9a8ffa8a59ed5ee)
